classrooms/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('classrooms.views',
	(r'^test/', 'test'),
)

urlpatterns += patterns('classrooms.ajax',
    (r'^createGroup/$', 'createGroup'),
    (r'^deleteGroup/$', 'deleteGroup'),
    (r'^changeGroupName/$', 'changeGroupName'),
    (r'^toggleLockGroup/$', 'toggleLockGroup'),
    (r'^joinGroup/$', 'joinGroup'),
    (r'^postMessage/$', 'postMessage'),
    (r'^deleteMessage/$', 'deleteMessage'),
    (r'^addAdminUsers/$', 'addAdminUsers'),
    (r'^adminDeleteUser/$', 'adminDeleteUser'),
    (r'^editProfile/$', 'editProfile'),
    (r'^getOldMessages/$', 'getOldMessages'),
    (r'^getNewMessages/$', 'getNewMessages'),
    (r'^changeGroupCode/$', 'changeGroupCode'),
    (r'^addTeacherSchool/$', 'addTeacherSchool'),
    (r'^avatarCrop/$', 'avatarCrop'),
    (r'^backgroundImageCrop/$', 'backgroundImageCrop'),
    
)

classrooms/models.py
import datetime

from django.contrib import admin
from django.contrib.auth.models import User
from django.db import models




class ConversationMessage(models.Model):
    text = models.TextField(max_length=150)
    timeDate = models.DateTimeField(auto_now=True)
    favorites = models.IntegerField(default=0, blank=True, null=True)
    
    
    def __unicode__(self):
      return u'%s' % (self.text)




class Message(models.Model):
    text = models.TextField(max_length=150)
    timeDate = models.DateTimeField(auto_now=True)
    retweets = models.IntegerField(default=0, blank=True, null=True)
    favorites = models.IntegerField(default=0, blank=True, null=True)
    ConversationMessages = models.ManyToManyField(ConversationMessage, blank=True, null=True)
    isRetweet = models.BooleanField(default=False)
    originalUser = models.ForeignKey(User, blank=True, null=True)
    
    
    def __unicode__(self):
      return u'%s' % (self.text)
    
    
    class Meta:
        ordering = ['-timeDate']
    

class HashTag(models.Model):
    tag = models.CharField(max_length=45)
    timeDate = models.DateTimeField(auto_now=True)
    messages = models.ManyToManyField(Message, blank=True, null=True)
    classroomID = models.IntegerField()
    
    
    def __unicode__(self):
      return u'%s' % (self.tag)


class Trending(models.Model):
    school = models.CharField(max_length=45, blank=True, null=True)
    hashtag1 = models.CharField(max_length=45, blank=True, null=True)
    hashtag2 = models.CharField(max_length=45, blank=True, null=True)
    hashtag3 = models.CharField(max_length=45, blank=True, null=True)
    hashtag4 = models.CharField(max_length=45, blank=True, null=True)
    hashtag5 = models.CharField(max_length=45, blank=True, null=True)
    hashtag6 = models.CharField(max_length=45, blank=True, null=True)
    hashtag7 = models.CharField(max_length=45, blank=True, null=True)
    hashtag8 = models.CharField(max_length=45, blank=True, null=True)
    hashtag9 = models.CharField(max_length=45, blank=True, null=True)
    hashtag10 = models.CharField(max_length=45, blank=True, null=True)
    timeDate = models.DateTimeField(auto_now=True)

    def __unicode__(self):
      return u'%s' % (self.school)
    
    
    
    
class PublicMessage(models.Model):
    school = models.CharField(max_length=45)
    messages = models.ManyToManyField(Message, blank=True, null=True)


    def __unicode__(self):
      return u'%s' % (self.school)
    
    
    
    
    
class Classroom(models.Model):
    name = models.CharField(max_length=45)
    code = models.CharField(max_length=10)
    messages = models.ManyToManyField(Message, blank=True, null=True)
    allowJoin = models.BooleanField(default=True)
    classOwnerID = models.IntegerField()


    def __unicode__(self):
      return u'%s' % (self.name)


class Following(models.Model):
    user = models.ForeignKey(User)


    def __unicode__(self):
      return u'%s %s' % (self.user.last_name, self.user.first_name)



class ClassUser(models.Model):
    user = models.ForeignKey(User)
    school = models.CharField(max_length=45, blank=True, null=True)
    teacher = models.BooleanField(default=True)
    readOnly = models.BooleanField(default=False)
    messages = models.ManyToManyField(Message, blank=True, null=True)
    classrooms = models.ManyToManyField(Classroom, blank=True, null=True)
    avatarBackColor = models.CharField(max_length=45, blank=True, null=True)
    avatarTextColor = models.CharField(max_length=45, blank=True, null=True)


    def __unicode__(self):
      return u'%s' % (self.user)
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

classrooms/views.py
import os
ROOT_PATH = os.path.dirname(__file__)

from django.shortcuts import render_to_response, redirect, get_object_or_404
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from classrooms.models import *
from classrooms import settings

from userInfo_profile.views import test_function


def test(request):
	getString = test_function()
	return HttpResponse(getString)
	
	
@login_required
def dashboard(request, classID=False):
    if ClassUser.objects.filter(user=request.user):
        classUser = ClassUser.objects.get(user=request.user)
    else:
        return redirect('/class/test/')
    
    #Get total number of messages made by user.
    if classUser.messages.all():
        messageCount = classUser.messages.all().count()
    else:
        messageCount = 0;
        
    #Get all users classes
    if classUser.classrooms.all():
        allClasses = classUser.classrooms.all()
    else:
        allClasses = False
        
    
    #Get Trending for the class
    if classID:
        if HashTag.objects.filter(classroomID=classID):
            trendings = HashTag.objects.filter(classroomID=classID).order_by('-timeDate')[:20]
        else:
            trendings = False
    elif allClasses:
        if HashTag.objects.filter(classroomID=allClasses[0].id):
            trendings = HashTag.objects.filter(classroomID=allClasses[0].id).order_by('-timeDate')[:20]
        else:
            trendings = False
    else:
        trendings = False
        
    
    #Get Current Class
    if classID:
        if Classroom.objects.filter(id=classID):
            currentClass = Classroom.objects.get(id=classID)
        else:
            currentClass = False
    elif allClasses:
        currentClass = allClasses[0]
    else:
        currentClass = False
        
    
    #Get Messages
    if currentClass:
        if currentClass.messages.all():
            messages = currentClass.messages.all().order_by('-timeDate')[0:20]
        else:
            messages = False
    else:
        messages = False
    
    return render_to_response('index.html', {
            'user':request.user,
            'classUser':classUser,
            'messageCount':messageCount,
            'allClasses':allClasses,
            'trendings':trendings,
            'currentClass':currentClass,
            'messages':messages,
        })







#---------------------------------- Special Functions ----------------------------------------


import string
from time import time
from itertools import chain
from random import seed, choice, sample


def generateCode(length=5, digits=3, upper=0, lower=2):
    seed(time())

    lowercase = string.lowercase.translate(None, "o")
    uppercase = string.uppercase.translate(None, "O")
    letters = "{0:s}{1:s}".format(lowercase, uppercase)

    password = list(
        chain(
            (choice(uppercase) for _ in range(upper)),
            (choice(lowercase) for _ in range(lower)),
            (choice(string.digits) for _ in range(digits)),
            (choice(letters) for _ in range((length - digits - upper - lower)))
        )
    )

    return "".join(sample(password, len(password)))

classrooms/templates/get_messages.html
			{% if messages %}
				{% for message in messages %}
					{% for messageUserInfo in message.classuser_set.all %}
				<li id="message{{ message.id }}" class="new-uploaded-message ui-corner-all custom-corners" data-options='{"messageID":{{ message.id }}}'>
					<div class="ui-bar ui-bar-b" {% if messageUserInfo.avatarBackColor %}style="background-color: {{ messageUserInfo.avatarBackColor }};color: {{ messageUserInfo.avatarTextColor }};"{% endif %}>

					  {% ifequal userInfo.id messageUserInfo.id %}
					  <h3 style="margin-top: 15px;">I posted this {{ message.timeDate|timesince }} ago</h3>
					  <span style="float: right;"><a href="#deleteTweetCheck" onclick="$('#yes_or_no').val('{{ message.id }}')" data-rel="popup" data-position-to="window" class="ui-btn ui-btn-a ui-mini ui-corner-all ui-btn-icon-notext ui-icon-delete ui-shadow" title="delete message"></a></span>
					  {% else %}
					  <h3>{{ messageUserInfo.user.first_name|capfirst }} {{ messageUserInfo.user.last_name|capfirst }} posted this {{ message.timeDate|timesince }} ago</h3>
					  {% endifequal %}
				  
					</div>
					<div class="ui-body ui-body-a new-uploaded-message-body">
					  <p class="message">{{ message.text }}</p>
					</div>
				</li>
					{% endfor %}
				{% endfor %}
			{% else %}
				Sorry, no more messages
			{% endif %}

classrooms/templates/post_message.html
<li id="message{{ message.id }}" class="new-uploaded-message ui-corner-all custom-corners" data-options='{"messageID":{{ message.id }}}'>
    <div class="ui-bar ui-bar-b" {% if userInfo.avatarBackColor %}style="background-color: {{ userInfo.avatarBackColor }};color: {{ userInfo.avatarTextColor }};"{% endif %}>
	<h3 style="margin-top: 15px;">I posted this {{ message.timeDate|timesince }} ago</h3>
	<span style="float: right;"><a href="#deleteTweetCheck" onclick="$('#yes_or_no').val('{{ message.id }}')" data-rel="popup" data-position-to="window" class="ui-btn ui-btn-a ui-mini ui-corner-all ui-btn-icon-notext ui-icon-delete ui-shadow" title="delete message"></a></span>
    </div>
    <div class="ui-body ui-body-a new-uploaded-message-body">
	<p class="message">{{ message.text }}</p>
    </div>
</li>